export const ADD_VOTE = "ADD_VOTE";
export const ADD_POLL = "ADD_POLL";
export const FECTH_POLL_LOADING = "FECTH_POLL_LOADING";
export const FECTH_POLL_FAILED = "FECTH_POLL_FAILED";
export const FETCHED_POLLS = 'FETCHED_POLLS';

export const FECTH_CATEGORIES_LOADING = 'FECTH_CATEGORIES_LOADING';
export const FECTH_CATEGORIES_FAILED = 'FECTH_CATEGORIES_FAILED';
export const FECTHED_CATEGORIES = 'FECTHED_CATEGORIES';
