export const REQUEST_VOTE = "REQUEST_VOTE";
export const REQUEST_VOTE_FAILED = "REQUEST_VOTE_FAILED";
export const REQUEST_VOTE_SUCCESS = "REQUEST_VOTE_SUCCESS";

export const FECTH_POLL_LOADING = "FECTH_POLL_LOADING";
export const FECTH_POLL_FAILED = "FECTH_POLL_FAILED";
export const FETCHED_POLLS = 'FETCHED_POLLS';

export const CREATE_POLL_REQUEST = "CREATE_POLL_REQUEST";
export const CREATE_POLL_FAILED = "CREATE_POLL_FAILED";
export const CREATE_POLL_SUCCESS = "CREATE_POLL_SUCCESS";

export const FECTH_CATEGORIES_LOADING = 'FECTH_CATEGORIES_LOADING';
export const FECTH_CATEGORIES_FAILED = 'FECTH_CATEGORIES_FAILED';
export const FECTHED_CATEGORIES = 'FECTHED_CATEGORIES';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED  = 'SIGNUP_FAILED';
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE1OWRkNzE2MWQ0ZDg2Y2JkM2FlMDAiLCJpYXQiOjE2NTU2NDkwODIsImV4cCI6MTY1NTY1MjY4Mn0.5S2CBd3O3205iP3WaXueLpnT7oixgMo_OjO4ceg8EZA admin
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFkZjUxNDBmOTc3NmYzMjhlYmZkZjIiLCJpYXQiOjE2NTU2NDkxNTUsImV4cCI6MTY1NTY1Mjc1NX0.-qYOJ6d-Zd17LG1SwdvbfyM27cfVNL_QQnKpDcgHHn8 client one
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFmMzNlN2ViMmE0N2M0OTA0YmZiYzMiLCJpYXQiOjE2NTU2NDkyNjQsImV4cCI6MTY1NTY1Mjg2NH0.eRQ9Rq7ghc3er1erREZVJHMReQROJ1KkujBS0oPGnuc Jogesh Puma
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFmMzQ0YmViMmE0N2M0OTA0YmZiYzgiLCJpYXQiOjE2NTU2NDkzNjUsImV4cCI6MTY1NTY1Mjk2NX0.DunOvWmOiVUW4g6R_ymgrCt4oVKt9pA37Qv3KK2fNds Janet Jackson
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFmMzQ5OWViMmE0N2M0OTA0YmZiY2QiLCJpYXQiOjE2NTU2NDk0NDIsImV4cCI6MTY1NTY1MzA0Mn0.WE4dhl6nyEHadwDmJ1oIYC2HKsjScjLmMfeAzVCCOCQ Emily Fowler
